Repository ajaysrinivas333/ProductFeedbackApp, pull requests merged in 2023-01, with the labels that each got.

#6 API : Product add
  src/backend/constants.ts
  src/backend/helpers.ts
  src/backend/models/product.ts
  src/pages/api/product/index.ts
  tsconfig.json
Labels: Feature

#7 Added fetch all products api
  src/pages/api/product/index.ts
Labels: Feature

#10 API refactors
  src/backend/helpers.ts
  src/backend/models/product.ts
  src/backend/models/user.ts
  src/backend/types/index.ts
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/auth/signup.ts
  src/pages/api/hello.ts
  src/pages/api/private/product/[productId].ts
  src/pages/api/private/product/index.ts
  src/pages/api/private/product/mine.ts
  src/pages/api/product/[productId].ts
  src/pages/api/public/product/index.ts
  tsconfig.json
Labels: Refactors

#12 Added category wise filter to product home page and some optimizations
  src/components/Navbar/Navbar.tsx
  src/components/Product/ProductCard.tsx
  src/components/User/UserRunDown.tsx
  src/pages/home/index.tsx
  src/styles/home.module.scss
Labels: Feature

#13 Added sortBy functionality in navbar
  src/components/Navbar/Navbar.tsx
  src/components/UI/Menu.tsx
  src/pages/home/index.tsx
  src/styles/globals.css
Labels: Feature

#14 Product tab view in homepage
  package.json
  src/pages/api/auth/[...nextauth].ts
  src/pages/home/index.tsx
  src/styles/globals.css
  src/styles/home.module.scss
Labels: Feature

#15 Add new product
  src/components/Navbar/Navbar.tsx
  src/components/Product/ProductForm.tsx
  src/components/UI/Input.tsx
  src/components/UI/Menu.tsx
  src/lib/constants.ts
  src/pages/add-product/index.tsx
  src/pages/home/index.tsx
  src/styles/addproduct.module.scss
  src/styles/authform.module.scss
  src/styles/navbar.module.scss
  src/styles/product-form.module.scss
Labels: Feature

#16 Added username from email formatter and tweaked signup validations
  src/lib/index.ts
  src/pages/api/auth/signup.ts
  src/pages/home/index.tsx
Labels: enhancement

#17 Homepage, Navbar & Product card tweaks.
  src/backend/helpers.ts
  src/components/Auth/AuthForm/index.tsx
  src/components/Auth/LoginText.tsx
  src/components/Product/ProductCard.tsx
  src/pages/add-product/index.tsx
  src/pages/home/index.tsx
  src/styles/globals.css
  src/styles/home.module.scss
  src/styles/navbar.module.scss
  src/styles/product-card.module.scss
Labels: enhancement, Refactors

#19 Added new feedback api
  src/backend/constants.ts
  src/backend/models/feedback.ts
  src/backend/types/index.ts
  src/pages/api/private/feedback/[productId].ts
Labels: Feature

#21 Added upvote/downvote api
  src/backend/models/feedback.ts
  src/pages/api/private/feedback/upvote.ts
Labels: Feature

#22 completed edit product functionality and added page loader
  src/components/Product/ProductCard.tsx
  src/components/Product/ProductForm.tsx
  src/components/UI/GlobalLoader.tsx
  src/hooks/use-page-loading.tsx
  src/pages/_app.tsx
  src/pages/add-product/index.tsx
  src/pages/api/private/product/[productId].ts
  src/pages/edit-product/index.tsx
  src/pages/home/index.tsx
  src/styles/addproduct.module.scss
  src/styles/globals.css
Labels: Feature

#23 Performance optimizations in product pages
  src/components/Auth/AuthGuard.tsx
  src/components/Product/ProductCard.tsx
  src/components/Product/ProductForm.tsx
  src/hooks/use-auth.tsx
  src/lib/index.ts
  src/pages/add-product/index.tsx
  src/pages/api/private/product/[productId].ts
  src/pages/api/revalidate.ts
  src/pages/auth/index.tsx
  src/pages/edit-product/index.tsx
  src/pages/home/index.tsx
Labels: enhancement

#24 Update feedback user-action API
  src/pages/api/private/feedback/index.ts
  src/pages/api/private/feedback/upvote.ts
Labels: Feature

#25 Restrict Product owner from adding feedback to own products
  src/pages/api/private/feedback/index.ts
Labels: enhancement

#26 Added product owner update status api
  src/backend/models/feedback.ts
  src/pages/api/private/feedback/update-status.ts
Labels: Feature

#28 Added signout button
  src/components/UI/Avatar.tsx
  src/components/User/UserRunDown.tsx
  src/pages/home/index.tsx
  src/styles/home.module.scss
Labels: Feature
