Repository ajaysrinivas333/ProductFeedbackApp, pull requests merged in 2023-03, with the labels that each got.

#38 Update comments count
  src/backend/models/comment.ts
  src/components/Comments/CommentSection.tsx
  src/pages/api/private/comment/index.ts
  src/pages/discussion/[feedbackId].tsx
Labels: enhancement

#39 Product Roadmap | API & Frontend
  package-lock.json
  package.json
  src/components/Feedback/FeedbackCard.tsx
  src/components/Navbar/Navbar.tsx
  src/components/RoadMap/RoadMapCard.tsx
  src/components/UI/Card.tsx
  src/hooks/use-auth.tsx
  src/hooks/use-upvote.tsx
  src/lib/index.ts
  src/pages/add-feedback/index.tsx
  src/pages/api/private/roadmap/[productId].ts
  src/pages/api/public/roadmap/[productId].ts
  src/pages/discussion/[feedbackId].tsx
  src/pages/feedbacks/[productId].tsx
  src/pages/home/index.tsx
  src/pages/roadmap/[productId].tsx
  src/styles/feedback-card.module.scss
  src/styles/navbar.module.scss
  src/styles/roadmap-page.module.scss
Labels: enhancement, Feature

#40 Fixed the undefined bug in Add Feedback page and Added CommentSection…
  src/components/Comments/CommentSection.tsx
  src/components/Feedback/FeedbackForm.tsx
  src/pages/discussion/[feedbackId].tsx
Labels: bug

#42 Added edit/delete options to feedback card
  src/components/Feedback/FeedbackCard.tsx
  src/styles/feedback-card.module.scss
Labels: enhancement

#43 Roadmap mobile screen
  src/components/Feedback/FeedbackCard.tsx
  src/components/RoadMap/RoadMapCard.tsx
  src/lib/constants.ts
  src/pages/feedbacks/[productId].tsx
  src/pages/roadmap/[productId].tsx
  src/styles/navbar.module.scss
  src/styles/roadmap-page.module.scss
Labels: Refactors
